### ISSUE TITLE
bug when you try to post an embedded video

### ISSUE THREAD

**Issue by klausn** [jyr/opentumblr#9]
Hi!

When I'm trying to post an embedded video via OpenTumblr, my Blog seems to have a bug:
All older posts following this video post are getting out of place, they all slip to the left side.
What's wrong in here? Please help me.
Thanks

**Comment by jyr** [comment]
Hi,

I need more data, could you paste de embebed code of the video.

**Comment by klausn** [comment]
I found the failure. It's in my template. Sorry, but great thanks for oyur response.

**Comment by jyr** [comment]
your welcome,
